# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Safevideokit
email: marketing@safevideokit.com 
showusps: true
safeui: true
pwa: true
developerKey: AIzaSyDr30lsukCywJXYYPSn5prs6FwvmgqQkxg
clientId: 762288849553-00jgfop7e3qqhabi7s7culrbc8ntohrs.apps.googleusercontent.com
appId: 762288849553
dropboxapikey: ctioixo2vm18z7u
description: >- # this means to ignore newlines until "baseurl:"
  Safevideokit.com is a game changing website for people who are in need to edit their videos.
  Safevideokit.com offers free online video editing services that does your job in no time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://safevideokit.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

siteurl: https://safevideokit.com
alternateName: safevideokit
logo: /assets/safevideokit.svg
pwalogo: /assets/safevideokit.svg

permalink: /blog/:title
paginate: '12'
paginate_path: '/blog/page:num/'
theme: appscms-tools-theme
# Build settings

theme: appscms-tools-theme
markdown: kramdown
plugins:
  - jekyll-feed
favicon: assets/safevideokit.svg
production_google_analytics: 'UA-179965937-17'
name: safevideokit
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
