[[headers]]
  for = "/*"
  [headers.values]
      Cross-Origin-Opener-Policy = "same-origin"
      Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/calc/sitemap.xml"
  to = "https://safevideokit-calc-develop.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/calc"
  to = "https://safevideokit-calc-develop.netlify.app"
  force = true
  status = 200

[[redirects]]
  from = "/calc*"
  to = "https://safevideokit-calc-develop.netlify.app/calc/:splat"
  force = true
  status = 200
